#####################################
# FOSS Scanner  using Blackduck server
### compile code
### publish scan results on blackduck server
### TODO: publish scan result to DevSecOps backend via REST API
#####################################

name: Blackduck scanner
on:
  # Triggers the workflow on push or pull request events
  push:
    # only for master branch
    branches: [ master ]
  pull_request:
    # only for master and test-github-actions branches
    branches: [ master, test-github-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # -- Build your project here -- eg. mvn clean package
      - name: Build simple java app with maven
        run: mvn -B package --file pom.xml

      # -- scan app with blackduck
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.0
        with:
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true --detect.project.name=AK-github-actions --detect.project.version.name=0.1'

  upload-results:
    # -- Read projects from Blackduck by running CGI customized client
    runs-on: ubuntu-latest
    needs: build-scan
    steps:
      #- uses: actions/checkout@v2
      #- name: Set up JDK 1.8
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 1.8
      - name: Read results form blackduck server and save it to DB
        run: |
          mvn package
          java -jar target/loan-approval-spring-boot-0.0.1-SNAPSHOT.jar --project.name=AK-github-actions --project.version=0.1
